fix: Compile-time error caused by non-weak yield
Error message to be fixed:

```
wiring_time.c:(.text.delay+0xc): undefined reference to `yield'
exit status 1
Error compiling for board Generic STM32F1 series.
```