[CI] Fix build failed management
Since arduino-cli v0.11.0 '-o' options has been removed.
The script does not handle properly this case which raised
a command usage error.

Error: unknown shorthand flag: 'o' in -o
Usage:
  arduino-cli compile [flags]

So this fix allows to properly handle it.

Signed-off-by: Frederic Pillon <frederic.pillon@st.com>